name: Build & Package
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build your software
        run: make   # Replace with your build command

      - name: Package the software
        run: tar -czvf output.tar.gz build/   # Example packaging step

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: packaged-software
          path: output.tar.gz
       - name: Check if artifact exists
          run: ls -l output.tar.gz